package com.dl.springcloud.base.entity;

import java.util.Date;

/**
 * BaseFileUpDown generated by hbm2java
 */
public class BaseFileUpDown implements java.io.Serializable {

	private Integer id;
	private String model;
	private String tablename;
	private Integer bzid;
	private Date createTime;
	private String state;
	private String type;
	
	public BaseFileUpDown() {
	}

	public BaseFileUpDown(String model, String tablename, Integer bzid,
			Date createTime, String state) {
		this.model = model;
		this.tablename = tablename;
		this.bzid = bzid;
		this.createTime = createTime;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getTablename() {
		return this.tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	public Integer getBzid() {
		return this.bzid;
	}

	public void setBzid(Integer bzid) {
		this.bzid = bzid;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	/**
	 * @return the type
	 */
	public String getType() {
		return type;
	}

	/**
	 * @param type the type to set
	 */
	public void setType(String type) {
		this.type = type;
	}

}
