package com.dl.springcloud.base.entity;

// default package
// Generated 2015-4-26 19:00:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BaseFile generated by hbm2java
 */
public class BaseFile implements java.io.Serializable {

	private Integer id;
	private Integer fileId;
	private String fileName;
	private String filePath;
	private String fileExt;
	private Long fileSize;
	private Date createTime;
	private String state;
	private String fileRemark;
	
	private BaseFileUpDown baseFileUpDown;
	@TempType
	private String modelName;
	
	public BaseFile() {
	}

	public BaseFile(int id) {
		this.id = id;
	}

	public BaseFile(Integer id, Integer fileId, String fileName, String filePath,
			String fileExt, Long fileSize, Date createTime, String state) {
		this.id = id;
		this.fileId = fileId;
		this.fileName = fileName;
		this.filePath = filePath;
		this.fileExt = fileExt;
		this.fileSize = fileSize;
		this.createTime = createTime;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public String getFileExt() {
		return this.fileExt;
	}

	public void setFileExt(String fileExt) {
		this.fileExt = fileExt;
	}

	public Long getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Long fileSize) {
		this.fileSize = fileSize;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	/**
	 * @return the baseFileUpDown
	 */
	public BaseFileUpDown getBaseFileUpDown() {
		return baseFileUpDown;
	}

	/**
	 * @param baseFileUpDown the baseFileUpDown to set
	 */
	public void setBaseFileUpDown(BaseFileUpDown baseFileUpDown) {
		this.baseFileUpDown = baseFileUpDown;
	}

	/**
	 * @return the modelName
	 */
	public String getModelName() {
		return modelName;
	}

	/**
	 * @param modelName the modelName to set
	 */
	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

	public String getFileRemark() {
		return fileRemark;
	}

	public void setFileRemark(String fileRemark) {
		this.fileRemark = fileRemark;
	}

 

}
