package com.dl.springcloud.system.entity;

import com.dl.springcloud.base.entity.BaseEntity;

/**
 * BaseMenu generated by hbm2java
 */
public class BaseMenu extends BaseEntity {

	private String text;
	private Integer parentid;
	private String parentName;
	private String url;
	private String ico;
	private String remark;
	
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public Integer getParentid() {
		return parentid;
	}
	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}
	public String getParentName() {
		return parentName;
	}
	public void setParentName(String parentName) {
		this.parentName = parentName;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String getIco() {
		return ico;
	}
	public void setIco(String ico) {
		this.ico = ico;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
}
