package com.dl.springcloud.system.entity;
import java.util.Date;
import java.util.List;
import java.util.Set;


/**
 * BaseUser generated by hbm2java
 * @author donglei
 * @date 2015-03-27
 */
public class BaseUser implements java.io.Serializable {
	 
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String userid;
	private String username;
	private String password;
	private String pssswordShow;
	private String phone;
	private Date createTime;
	private Date updateTime;
	private String state;
	private Integer membersExtId;
	private List<BaseRole> roles;
	private String headUrl;
	private String email;
	public BaseUser() {
	}

	public BaseUser(int id) {
		this.id = id;
	}
	

	public BaseUser(int id, String userid, String username, String password,
			String pssswordShow, String phone, Date createTime,
			Date updateTime, String state,Integer membersExtId) {
		this.id = id;
		this.userid = userid;
		this.username = username;
		this.password = password;
		this.pssswordShow = pssswordShow;
		this.phone = phone;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.state = state;
		this.membersExtId = membersExtId;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPssswordShow() {
		return pssswordShow;
	}

	public void setPssswordShow(String pssswordShow) {
		this.pssswordShow = pssswordShow;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Integer getMembersExtId() {
		return membersExtId;
	}

	public void setMembersExtId(Integer membersExtId) {
		this.membersExtId = membersExtId;
	}


	public List<BaseRole> getRoles() {
		return roles;
	}

	public void setRoles(List<BaseRole> roles) {
		this.roles = roles;
	}

	public String getHeadUrl() {
		return headUrl;
	}

	public void setHeadUrl(String headUrl) {
		this.headUrl = headUrl;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	
	 

}
