package com.dl.springcloud.system.entity;

import com.dl.springcloud.base.entity.BaseEntity;

/**
 * BaseDic generated by hbm2java
 */
public class BaseDic extends BaseEntity {

	
	private String dicCode;
	
	private String dicValue;
	
	private String dicText;
	
	private String dicType;

	public BaseDic() {
	}
   
	public String getDicCode() {
		return this.dicCode;
	}

	public void setDicCode(String dicCode) {
		this.dicCode = dicCode;
	}

	public String getDicValue() {
		return this.dicValue;
	}

	public void setDicValue(String dicValue) {
		this.dicValue = dicValue;
	}

	public String getDicText() {
		return this.dicText;
	}

	public void setDicText(String dicText) {
		this.dicText = dicText;
	}

	/**
	 * @return the dicType
	 */
	public String getDicType() {
		return dicType;
	}

	/**
	 * @param dicType the dicType to set
	 */
	public void setDicType(String dicType) {
		this.dicType = dicType;
	}

	
}
