package com.dl.springcloud.system.entity;

// default package
// Generated 2015-5-11 22:45:38 by Hibernate Tools 3.4.0.CR1

/**
 * BaseUserRole generated by hbm2java
 */
public class BaseUserRole implements java.io.Serializable {

	private Integer rid;
	private Integer baseUserId;
	private Integer baseRoleId;

	public BaseUserRole() {
	}

	public BaseUserRole(Integer baseUserId, Integer baseRoleId) {
		this.baseUserId = baseUserId;
		this.baseRoleId = baseRoleId;
	}

	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	public Integer getBaseUserId() {
		return this.baseUserId;
	}

	public void setBaseUserId(Integer baseUserId) {
		this.baseUserId = baseUserId;
	}

	public Integer getBaseRoleId() {
		return this.baseRoleId;
	}

	public void setBaseRoleId(Integer baseRoleId) {
		this.baseRoleId = baseRoleId;
	}

}
