package com.dl.springcloud.system.entity;

 
import java.util.Date;
import java.util.List;
import java.util.Set;

/**
 * BaseRole generated by hbm2java
 */
@SuppressWarnings("serial")
public class BaseRole implements java.io.Serializable {

	
	private Integer id;
	private String name;
	private String code;
	private String type;
	private String state;
	private String remark;
	private Date createTime;
	private List<BaseUser> users;
	
	public BaseRole() {
	}

	public BaseRole(int id) {
		this.id = id;
	}

	public BaseRole(int id, String name, String code, String type, String remark,
			String state, Date createTime) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.type = type;
		this.state = state;
		this.createTime = createTime;
		this.remark = remark;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public List<BaseUser> getUsers() {
		return users;
	}

	public void setUsers(List<BaseUser> users) {
		this.users = users;
	}

	 

 
}
